version: "3.7"

volumes:
  prometheus_data: {}

networks:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-admin-api"
    ports:
      - 9090:9090
    links:
      - ping-mtu-exporter:ping-mtu-exporter
    depends_on: []
    networks:
      - back-tier
    restart: always

  ping-mtu-exporter:
    build: ./ping_mtu_exporter/.
    environment:
      - SERVER_PORT=8080
      - SUBTRACT_HEADERS=True
    ports:
      - 8080:8080
    networks:
      - back-tier
    restart: always
